name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-lowest-version:
    name: Build lowest version
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@1.7.0
        with:
          php-version: '7.2'
          coverage: xdebug
          ini-values: xdebug.overload_var_dump=1
          extensions: mbstring, intl
          tools: prestissimo

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: composer update --no-interaction --prefer-stable --prefer-lowest --prefer-dist

      - name: Run tests
        run: ./vendor/bin/phpunit

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0']

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@1.7.0
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          ini-values: xdebug.overload_var_dump=1
          extensions: mbstring, intl

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: composer update --no-interaction --prefer-dist

      - name: Run tests
        run: ./vendor/bin/phpunit
